"""Temp bootstrap file to run K&A"""
import pathhack

from datasets import testloader
from initialisations import khanahmad2004 as ka

# dataset = testloader.load_fossil()
# dataset = testloader.load_iris()

# The normalised fossil generated by their Java
dataset = testloader._load_local('fossil_ccia')

# Fossil and Iris both have 3
num_clusters = 3

centroids = ka.generate(dataset.data, num_clusters)

# print(centroids)
